// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://ylckqcrtzubnjuvpyhbi.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InlsY2txY3J0enVibmp1dnB5aGJpIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDYzODc3NTcsImV4cCI6MjA2MTk2Mzc1N30.hEl_hZrXhFGhgVVpNZL9M7b6X98TNRIyUc0HpCgnU9U";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);